/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Font;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

import apphandler.TransactionHandler;
import apphandler.TransactionListener;

/**
 *
 * @author Anirudh
 */
public class CustomerScreen extends javax.swing.JInternalFrame implements TransactionListener {

    /**
     * Creates new form CustomerScreen
     */
    public CustomerScreen() {
        initComponents();
        
        setClosable(true);
    }
    
    private TransactionHandler handler = new TransactionHandler();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setBounds(82, 59, 80, 22);
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setBounds(82, 93, 180, 22);
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setBounds(326, 176, 257, 26);
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane2.setBounds(164, 214, 515, 180);
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel1.setText("Welcome!");

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel2.setText("Your A/C number: "+Login.currentUser.getAccount());

        format.setMaximumFractionDigits(2);
        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel4.setText("TRANSACTION SUMMARY");

        transactions = handler.getTransactions(Login.currentUser.getAccount());
        double totalDebits = 0.0;
        double totalCredits = 0.0;
        for(Object[] transaction : transactions) {
        	try{
        		totalCredits += Double.parseDouble((String)transaction[2]);
        	}catch(Exception e) {}
        	
        	try{
        		totalDebits += Double.parseDouble((String)transaction[3]);
        	}catch(Exception e) {}
        }
        
        Login.currentUser.setBalance(totalCredits - totalDebits);
        
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
        	transactions,
            new String [] {
                "Date", "Description", "Credit", "Debit"
            }
        ));
        jLabel2.setSize(400, 30);
        jScrollPane2.setViewportView(jTable2);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel2);
        getContentPane().add(jLabel1);
        getContentPane().add(jLabel4);
        getContentPane().add(jScrollPane2);
        
        lblYourBalance.setText("Your Balance: " + format.format(Login.currentUser.getBalance()));
        lblYourBalance.setFont(new Font("Consolas", Font.PLAIN, 18));
        lblYourBalance.setBounds(82, 127, 403, 22);
        getContentPane().add(lblYourBalance);
        
        setSize(800,500);

        //pack();
    }// </editor-fold>//GEN-END:initComponents

    JLabel lblYourBalance = new JLabel();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;

	
	@Override
	public void transaction(double amount, int fromAcct, int toAcct) {
		if(fromAcct == Login.currentUser.getAccount()) {
			double balance  = Login.currentUser.getBalance();
			Login.currentUser.setBalance(balance - amount);
			updateBalance(sdf.format(new Date()), "To Ac: "+toAcct, "", format.format(amount));
		}
		if(toAcct == Login.currentUser.getAccount()) {
			double balance  = Login.currentUser.getBalance();
			Login.currentUser.setBalance(balance + amount);
			updateBalance(sdf.format(new Date()), "From Ac: "+fromAcct, "", format.format(amount));
		}
	}
	
	private void updateBalance(String dt, String description, String credit, String debit) {
		lblYourBalance.setText("Your Balance: " + format.format(Login.currentUser.getBalance()));
		lblYourBalance.invalidate();
		
		if(transactions != null) {
			DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
			Object[] row = {dt, description, credit, debit};
			model.addRow(row);
		}
	}
	
	SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
	NumberFormat format = NumberFormat.getInstance();
	Object[][] transactions = null;

	public static void main(String[] args) {
		SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
		System.out.println(sdf.format(new Date()));
	}
}

