/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Font;

import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.WindowConstants;

import dao.UserDAO;
import apphandler.LoginHandler;
import businessobject.User;

/**
 *
 * @author Anirudh
 */
public class UserAccntCreation extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserAccntCreation
     */
    public UserAccntCreation() {
    	setSize(1000,700);
        initComponents();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setClosable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel6.setBounds(223, 299, 112, 24);
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton1.setBounds(359, 185, 61, 23);
        jLabel7 = new javax.swing.JLabel();
        jLabel7.setBounds(223, 264, 91, 24);
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton2.setBounds(513, 185, 76, 23);
        jLabel8 = new javax.swing.JLabel();
        jLabel8.setBounds(223, 334, 91, 24);
        jLabel10 = new javax.swing.JLabel();
        jLabel10.setBounds(223, 399, 49, 24);
        jLabel9 = new javax.swing.JLabel();
        jLabel9.setBounds(223, 369, 91, 24);
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setBounds(359, 399, 251, 135);
        address = new javax.swing.JTextArea();
        age = new javax.swing.JTextField();
        age.setBounds(359, 144, 251, 28);
        fullName = new javax.swing.JTextField();
        fullName.setBounds(359, 69, 251, 28);
        jLabel11 = new javax.swing.JLabel();
        jLabel11.setBounds(223, 551, 105, 24);
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setBounds(223, 73, 70, 27);
        motherName = new javax.swing.JTextField();
        motherName.setBounds(359, 364, 251, 28);
        accType = new javax.swing.JComboBox();
        accType.setBounds(359, 546, 251, 28);
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setBounds(223, 151, 56, 21);
        dateOfBirth = new javax.swing.JTextField();
        dateOfBirth.setBounds(359, 259, 251, 28);
        jbtnReset = new javax.swing.JButton();
        jbtnReset.setBounds(582, 601, 107, 35);
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setBounds(223, 188, 48, 24);
        idProof = new javax.swing.JTextField();
        idProof.setBounds(359, 294, 251, 28);
        jbtnCreateAccount = new javax.swing.JButton();
        jbtnCreateAccount.setBounds(312, 601, 214, 34);
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setBounds(243, 21, 331, 62);
        fatherName = new javax.swing.JTextField();
        fatherName.setBounds(359, 329, 251, 28);
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setBounds(223, 223, 70, 24);
        occupation = new javax.swing.JTextField();
        occupation.setBounds(359, 218, 251, 28);

        ButtonGroup bg = new ButtonGroup();
    	bg.add(jRadioButton1);
    	bg.add(jRadioButton2);
    	
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel6.setText("TYPE OF ID PROOF");

        jRadioButton1.setText("Male");

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel7.setText("DATE OF BIRTH");

        jRadioButton2.setText("Female");
        

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel8.setText("FATHER'S NAME");

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel10.setText("ADDRESS");

        jLabel9.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel9.setText("MOTHER'S NAME");

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        jLabel11.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel11.setText("TYPE OF ACCOUNT");

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel1.setText("FULL NAME");

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel2.setText("AGE");

        jbtnReset.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jbtnReset.setText("RESET");
        

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel3.setText("GENDER");

        jbtnCreateAccount.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jbtnCreateAccount.setText("CREATE ACCOUNT");
        
        jbtnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreateAccountActionPerformed(evt);
            }
        });
        
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel4.setText("           ACCOUNT CREATION FORM");

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel5.setText("OCCUPATION");
        
        accType.addItem("SAVINGS");
        accType.addItem("CURRENT");
        
        
        getContentPane().setLayout(null);
        getContentPane().add(jLabel8);
        getContentPane().add(fatherName);
        getContentPane().add(jLabel6);
        getContentPane().add(idProof);
        getContentPane().add(jLabel1);
        getContentPane().add(fullName);
        getContentPane().add(jLabel2);
        getContentPane().add(age);
        getContentPane().add(jLabel3);
        getContentPane().add(jLabel5);
        getContentPane().add(jLabel7);
        getContentPane().add(dateOfBirth);
        getContentPane().add(occupation);
        getContentPane().add(jRadioButton1);
        getContentPane().add(jRadioButton2);
        getContentPane().add(jLabel9);
        getContentPane().add(jLabel10);
        getContentPane().add(jLabel11);
        getContentPane().add(motherName);
        getContentPane().add(jScrollPane1);
        getContentPane().add(accType);
        getContentPane().add(jbtnCreateAccount);
        getContentPane().add(jbtnReset);
        getContentPane().add(jLabel4);
        
        JLabel lblUserId = new JLabel();
        lblUserId.setText("USER ID & PASSWD");
        lblUserId.setFont(new Font("Consolas", Font.BOLD, 12));
        lblUserId.setBounds(223, 112, 124, 27);
        getContentPane().add(lblUserId);
        
        userId = new JTextField();
        userId.setBounds(359, 108, 124, 28);
        getContentPane().add(userId);
        
        password = new JTextField();
        password.setBounds(486, 109, 124, 28);
        getContentPane().add(password);

        //pack();
    }// </editor-fold>//GEN-END:initComponents

    private LoginHandler loginHandler = new LoginHandler();
    private void jbtnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreateAccountActionPerformed
    	int ageInt = 0;
    	String gender = gender = jRadioButton2.isSelected()?"F":"M";
    	
    	try{
    		ageInt = Integer.parseInt(age.getText());
    	} catch(Exception e) {System.err.println(e);}
    	
    	if(userId.getText().trim().equals("") || password.getText().trim().equals("")
    			|| fullName.getText().trim().equals("") || ageInt < 18) {
    		JOptionPane.showMessageDialog(null, "Invalid Details. Provide proper user id, password, full name and age.",
					"Account Creation Error", JOptionPane.ERROR_MESSAGE);
    		return;
    	}
    	
    	int retCode = loginHandler.createUser(userId.getText(),
    			password.getText(),
    			fullName.getText(),
    			ageInt,
		    	gender,
		    	occupation.getText(),
		    	dateOfBirth.getText(),
		    	idProof.getText(),
		    	fatherName.getText(),
		        motherName.getText(),
		        address.getText(),
		        accType.getSelectedItem().toString());

		if (retCode == UserDAO.USER_CREATED) {
			JOptionPane.showMessageDialog(null, "User created successfully",
					"User Created", JOptionPane.INFORMATION_MESSAGE);
		} else if (retCode == UserDAO.USER_EXISTS) {
			JOptionPane.showMessageDialog(null, "User Id already exists",
					"User Creation Failed", JOptionPane.ERROR_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(null, "User creation failed. Check logs for errors.",
					"User Creation Error", JOptionPane.ERROR_MESSAGE);
			jbtnResetActionPerformed(null);
		}
       
    }
    
    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreateAccountActionPerformed
    	userId.setText("");
    	password.setText("");
    	fullName.setText("");
    	jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        address.setText("");
        age.setText("");
        dateOfBirth.setText("");
        motherName.setText("");
        idProof.setText("");
        fatherName.setText("");
        accType.setSelectedIndex(0);
        occupation.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField dateOfBirth;
    private javax.swing.JTextField fullName;
    private javax.swing.JTextField motherName;
    private javax.swing.JTextField idProof;
    private javax.swing.JTextField fatherName;
    private javax.swing.JComboBox accType;
    private javax.swing.JTextField occupation;
    private javax.swing.JButton jbtnCreateAccount;
    private javax.swing.JButton jbtnReset;
    private JTextField userId;
    private JTextField password;
}
